[project]
name = "backend-todo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "fastapi[standard]>=0.117.1",
    "sqlalchemy>=2.0.43",
    "uvicorn[standard]>=0.36.0",
]
