[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "pydantic>=2.11.8",
    "sqlalchemy>=2.0.43",
    "uvicorn[standard]>=0.35.0",
]
